In [1]:
!pip3 install torch

# TENSOR

In [2]:
import torch
import numpy as np

## Tensor 초기화
- Tensor는 자료구조의 형태
- NumPy의 ndarray와 매우 유사


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
## tensor 라는 배열, 행렬과 유사한구조의 자료구조

In [4]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
np_array = np.array(data)
x_np = torch.tensor(np_array) ## 배열형태 뿐만아니라, numpy 형태도 Tesor로 변환가능하다
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [6]:
print(data)

[[1, 2], [3, 4]]


In [7]:
x_ones = torch.ones_like(x_data) ## torch화 할떄 모든 데이터 1로 변환
print(f'ones = {x_ones}')

x_rand = torch.rand_like(x_data, dtype=torch.float) # torch화 할때 모든데이터 rand(정규분포에 따른다.)
print(f"rand = {x_rand}")

# 특별히 torch.tensor를 하면 데이터 그대로, 값을 다른값으로 배열 모양은 같게 할수 있다.

ones = tensor([[1, 1],
        [1, 1]])
rand = tensor([[0.7639, 0.3003],
        [0.5518, 0.5327]])


In [8]:
shape = (3,3)
t_r = torch.rand(shape)
t_o = torch.ones(shape)
t_z = torch.zeros(shape)

print(f"{t_r}\n {t_o}\n {t_z}")

tensor([[0.0775, 0.3179, 0.2499],
        [0.7375, 0.2444, 0.2552],
        [0.7123, 0.4438, 0.3465]])
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성

In [9]:
tensor = torch.rand(3,4)

print(f"shape = {tensor.shape}") # shape 볼수 있다.
print(f"d_type = {tensor.dtype}") # datatype
print(f"device = {tensor.device}") # device 볼수 있다.(어느장치에 저장되어있는지)

shape = torch.Size([3, 4])
d_type = torch.float32
device = cpu


In [12]:
if torch.cuda.is_available(): #gpu가 존재하면
  tensor = tensor.to('cuda') #저장위치 cuda로
  print(tensor.device) #저장위치 변경

cuda:0


In [22]:
# numpy식 인덱싱 슬라이싱과 동일
tensor = torch.ones(4,4)
tensor[1,:] = 0
tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
# 텐서 합치기 가능
t1 = torch.cat([tensor, tensor, tensor],dim=1) #dim=1 가로 붙이기 0가 defalut 세로붙이기
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
## 텐서 곱하기

print(f"{tensor.mul(tensor)}\n {tensor*tensor}")
tensor.matmul(tensor.T), tensor @ tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


(tensor([[4., 0., 4., 4.],
         [0., 0., 0., 0.],
         [4., 0., 4., 4.],
         [4., 0., 4., 4.]]), tensor([[3., 3., 3., 3.],
         [0., 0., 0., 0.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [36]:
## 바꿔치기 연산
print(tensor)
tensor += 5 ## tensor.add_(5)
print(tensor)


tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


## Numpy로 변환

In [40]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy() ## tensor --> numpy
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [41]:
t.add_(1)
print(f"{t}\n {n}") # 같이 변한다.

tensor([2., 2., 2., 2., 2.])
 [2. 2. 2. 2. 2.]


In [43]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)