In [1]:
!pip3 install torch

# TENSOR

In [2]:
import torch
import numpy as np

## Tensor 초기화
- Tensor는 자료구조의 형태
- NumPy의 ndarray와 매우 유사


In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
## tensor 라는 배열, 행렬과 유사한구조의 자료구조

In [4]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
np_array = np.array(data)
x_np = torch.tensor(np_array) ## 배열형태 뿐만아니라, numpy 형태도 Tesor로 변환가능하다
print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [6]:
print(data)

[[1, 2], [3, 4]]


In [7]:
x_ones = torch.ones_like(x_data) ## torch화 할떄 모든 데이터 1로 변환
print(f'ones = {x_ones}')

x_rand = torch.rand_like(x_data, dtype=torch.float) # torch화 할때 모든데이터 rand(정규분포에 따른다.)
print(f"rand = {x_rand}")

# 특별히 torch.tensor를 하면 데이터 그대로, 값을 다른값으로 배열 모양은 같게 할수 있다.

ones = tensor([[1, 1],
        [1, 1]])
rand = tensor([[0.4288, 0.0640],
        [0.1585, 0.1471]])


In [8]:
shape = (3,3)
t_r = torch.rand(shape)
t_o = torch.ones(shape)
t_z = torch.zeros(shape)

print(f"{t_r}\n {t_o}\n {t_z}")

tensor([[0.2205, 0.9362, 0.8257],
        [0.2511, 0.3531, 0.9187],
        [0.2110, 0.1959, 0.5587]])
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성

In [9]:
tensor = torch.rand(3,4)

print(f"shape = {tensor.shape}") # shape 볼수 있다.
print(f"d_type = {tensor.dtype}") # datatype
print(f"device = {tensor.device}") # device 볼수 있다.(어느장치에 저장되어있는지)

shape = torch.Size([3, 4])
d_type = torch.float32
device = cpu


In [10]:
if torch.cuda.is_available(): #gpu가 존재하면
  tensor = tensor.to('cuda') #저장위치 cuda로
  print(tensor.device) #저장위치 변경

cuda:0


In [11]:
# numpy식 인덱싱 슬라이싱과 동일
tensor = torch.ones(4,4)
tensor[1,:] = 0
tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
# 텐서 합치기 가능
t1 = torch.cat([tensor, tensor, tensor],dim=1) #dim=1 가로 붙이기 0가 defalut 세로붙이기
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
## 텐서 곱하기

print(f"{tensor.mul(tensor)}\n {tensor*tensor}")
tensor.matmul(tensor.T), tensor @ tensor

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


(tensor([[4., 0., 4., 4.],
         [0., 0., 0., 0.],
         [4., 0., 4., 4.],
         [4., 0., 4., 4.]]), tensor([[3., 3., 3., 3.],
         [0., 0., 0., 0.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [14]:
## 바꿔치기 연산
print(tensor)
tensor += 5 ## tensor.add_(5)
print(tensor)


tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


## view
- tensor의 크기나 size 변경

In [20]:
x = torch.randn(4,5)
y = x.view(20)
z = x.view(5,-1)
print(x.size())
print(y.size())
print(z.size()) #사이즈 변경
print(x)
print(y)
print(z) #사이즈 변경


torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])
tensor([[ 1.1327, -0.4452, -0.6170,  0.4512, -0.7072],
        [-0.0846,  0.8153,  0.4053, -1.1105, -0.1524],
        [-0.5945, -2.3842, -0.2703, -1.0659,  1.3073],
        [ 1.1176,  0.7335,  0.6620,  0.0911,  0.4731]])
tensor([ 1.1327, -0.4452, -0.6170,  0.4512, -0.7072, -0.0846,  0.8153,  0.4053,
        -1.1105, -0.1524, -0.5945, -2.3842, -0.2703, -1.0659,  1.3073,  1.1176,
         0.7335,  0.6620,  0.0911,  0.4731])
tensor([[ 1.1327, -0.4452, -0.6170,  0.4512],
        [-0.7072, -0.0846,  0.8153,  0.4053],
        [-1.1105, -0.1524, -0.5945, -2.3842],
        [-0.2703, -1.0659,  1.3073,  1.1176],
        [ 0.7335,  0.6620,  0.0911,  0.4731]])


## item
- 텐서의 값이 하나라도 존재하면 숫자값을 얻을수 있음

In [23]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.5573])
-1.557327389717102
torch.float32


In [24]:
x = torch.randn(2) 
print(x)
print(x.item())#하나의 값만 가지고 올수 있다.
print(x.dtype)

tensor([2.5861, 0.7604])


ValueError: ignored

## squeeze
- 차원축소

In [27]:
tensor = torch.rand(1,3,3)
print(tensor.shape)
print(tensor)

torch.Size([1, 3, 3])
tensor([[[0.0621, 0.3494, 0.0276],
         [0.1496, 0.2616, 0.7866],
         [0.4137, 0.7315, 0.7304]]])


In [28]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.0621, 0.3494, 0.0276],
        [0.1496, 0.2616, 0.7866],
        [0.4137, 0.7315, 0.7304]])
torch.Size([3, 3])


## unsqueeze
- 차원을 증가

In [29]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.9012, 0.5460, 0.9687],
         [0.2272, 0.8293, 0.0386],
         [0.5149, 0.5855, 0.4449]]])
torch.Size([1, 3, 3])


In [32]:
t = tensor.unsqueeze(dim=0) #0 1 2....

print(t)
print(t.shape)

tensor([[[[0.9012, 0.5460, 0.9687],
          [0.2272, 0.8293, 0.0386],
          [0.5149, 0.5855, 0.4449]]]])
torch.Size([1, 1, 3, 3])


## stack

In [33]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## cat

In [34]:
a = torch.randn(1, 1, 3,3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a,b), dim=0)
print(c)
print(c.size())

tensor([[[[-1.4862,  1.3793,  1.1235],
          [ 1.1183, -0.4869,  2.0955],
          [ 0.5475,  0.0107, -0.7318]]],


        [[[-0.6779,  0.8750,  1.0543],
          [-0.4169, -1.0245,  1.2099],
          [ 1.5462, -0.9782, -0.1682]]]])
torch.Size([2, 1, 3, 3])


In [37]:
a = torch.randn(1, 3,3)
b = torch.randn(1, 3, 3)
c = torch.cat((a,b), dim=0) # dim 어디 추가할건지
print(c)
print(c.size())

tensor([[[-0.6632,  0.7321, -1.9165],
         [ 0.1374,  0.5053,  1.6921],
         [-0.1180,  0.5755, -1.4824]],

        [[ 0.5649,  0.4495, -0.2540],
         [-0.0783,  1.8220,  0.5635],
         [-1.8753, -0.5029,  0.5981]]])
torch.Size([2, 3, 3])


## chunk
- 텐서를 여러 개로 나룰 때 사용
- 몇개의 텐서로 나눌것이냐

In [43]:
tensor = torch.randn(3,6)
t1, t2, t3 = torch.chunk(tensor,3,dim=1)
print(tensor)
print(tensor.shape)
print(t1)
print(t2)
print(t3)

tensor([[ 0.6083, -2.9330,  0.6086,  0.2429,  1.0682,  1.2160],
        [-0.4872,  0.0252,  1.1551, -1.3903, -1.1649,  0.5762],
        [ 0.2406,  1.3220,  0.1098,  0.1549,  1.8842,  1.6862]])
torch.Size([3, 6])
tensor([[ 0.6083, -2.9330],
        [-0.4872,  0.0252],
        [ 0.2406,  1.3220]])
tensor([[ 0.6086,  0.2429],
        [ 1.1551, -1.3903],
        [ 0.1098,  0.1549]])
tensor([[ 1.0682,  1.2160],
        [-1.1649,  0.5762],
        [ 1.8842,  1.6862]])


## split
- chunck 와 동일 조금 다름
- 하나의 텐서당 크기가 얼마이냐

In [44]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1) #하나의 텐서의 크기를 얼마로 정할건지 3
print(tensor)
print(t1)
print(t2)

# 개수가 아닌 크기로 나눈다.

tensor([[0.8277, 0.8065, 0.6160, 0.5783, 0.9654, 0.4354],
        [0.7737, 0.1710, 0.8755, 0.3119, 0.3309, 0.9303],
        [0.3491, 0.7189, 0.0223, 0.5946, 0.3768, 0.5165]])
tensor([[0.8277, 0.8065, 0.6160],
        [0.7737, 0.1710, 0.8755],
        [0.3491, 0.7189, 0.0223]])
tensor([[0.5783, 0.9654, 0.4354],
        [0.3119, 0.3309, 0.9303],
        [0.5946, 0.3768, 0.5165]])


## torch <=> numpy
- Torch Tensor 를 numpy array 로 변환가능
- 메모리 공유하므로 서로 같이 변한다

In [49]:
 a = torch.ones(7)
 print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [50]:
b= a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [51]:
a.add_(1) #inplace method
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [52]:
import numpy

a = np.ones(7)
b = torch.from_numpy(a)
c = torch.tensor(a)
np.add(a, 1, out=a)
print(a)
print(b)
print(c)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


## CUDA Tensors
- .to 메소드를 사용하여 텐서를 어떠한 장치로 옮길수 잇음

In [56]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)
print(x.device)

tensor([-0.4197])
-0.419746994972229
torch.float32
cpu


In [57]:
device = torch.device('cuda' if torch.cuda.is_available() else "cpu") # gpu 환경여부 확인
print(device)

y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)
print(z.to('cpu',torch.double))

cuda
tensor([0.5803], device='cuda:0')
tensor([0.5803], dtype=torch.float64)
